model: "yolov8n-cls.pt"
type: "yolo"
train:
  batch: -1
  data: /datasets/clasificacion/colorball.v8i.multiclass/
  epochs: 1
  imgsz: 640
# val:
#   conf: 0.01
# test:
#   conf: 0.01
sweeper:
  version: 1
  algorithm: optuna
  direction: maximize
  study_name: "color_ball_v2"
  tune: true
  sampler: "TPESampler"
  n_trials: 1
  search_space:
    model: [ "choice", "yolov8n-cls.pt" ]
    train:
      imgsz: [ "choice", 416 ]
      lr0: [ "loguniform", 1e-5, 1e-2 ]
extras:
  gpu:
    id: 0
    limit: 0.95
metadata:
  content: "Este es un experimento de clasificación de imágenes."
  author: "William Rodriguez"
  documentation: "Este modelo fue entrenado con datos del 2025."
