debug: wisrovi

model: "yolov8n-cls.pt"

#dvc_data_path: /datasets/clasificacion//colorball.v8i.multiclass.dvc
train:
  #batch: -1
  data: /datasets/clasification/colorball.v8i.multiclass/
  epochs: 1
  imgsz: 640
sweeper:
  version: 2
  #algorithm: optuna
  #direction: maximize
  study_name: "example_clasification"
  #sampler: "TPESampler"
  fitness: "metrics/accuracy_top1"
  n_trials: 5
  search_space:
    model: ["choice", "yolov8n-cls.pt"]
    train:
      imgsz: ["choice", 416, 512, 640, 720, 920, 1024]
      lr0: ["loguniform", 1e-5, 1e-2]
metadata:
  content: "Este es un experimento de clasificación de imágenes."
  author: "William Rodriguez"
  documentation: "Este modelo fue entrenado con datos del 2025."
mlflow:
  MLFLOW_TRACKING_URI: http://localhost:5000
minio:
  MINIO_ENDPOINT: http://localhost:9000
  MINIO_ID: minioadmin
  MINIO_SECRET_KEY: minioadmin
task_id: test_system_metrics_demo