model: yolov8n-cls.pt
type: yolo
train:
  data: /tmp/test_dataset
  epochs: 1
  imgsz: 64
  batch: 4
task_id: test_system_metrics
sweeper:
  study_name: test_experiment
mlflow:
  MLFLOW_TRACKING_URI: http://localhost:5000
minio:
  MINIO_ENDPOINT: http://localhost:9000
  MINIO_ID: testkey
  MINIO_SECRET_KEY: testsecret