model: "yolov8n-seg.pt"
type: "yolo"
# dvc_data_path: /datasets/clasificacion/colorball.v8i.multiclass.dvc
train:
  batch: -1
  data: /datasets/segmentacion/ArchitecturePlan/data.yaml
  epochs: 2
  imgsz: 640
sweeper:
  version: 1
  algorithm: optuna
  direction: maximize
  study_name: "example_segmentation"
  sampler: "TPESampler"
  fitness: "metrics/mAP50(M)"
  n_trials: 1
  search_space:
    #model: ["choice", "yolov8n-seg.pt", "yolov8s-seg.pt", "yolov8m-seg.pt"]
    train:
      imgsz: ["choice", 640]
      #lr0: ["loguniform", 1e-5, 1e-2]
      #momentum: ["range", 0.85, 0.98, 0.01]
      #freeze: ["range", 1, 5, 1]
      #optimizer: ["choice", SGD, Adam, AdamW, NAdam, RMSProp]
extras:
  gpu:
    id: 0
    limit: 0.60
metadata:
  content: "Este es un entrenamiento de prueba de manuel"
  author: "Manu G"
  documentation: "Este modelo fue entrenado con datos de marzo 2025."
